<?php

declare(strict_types=1);

/*
 * ExcitesmsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ExcitesmsLib\Tests;

class ClientFactory
{
    public static function create(HttpCallBackCatcher $httpCallback): \ExcitesmsLib\ExcitesmsClient
    {
        return (new \ExcitesmsLib\ExcitesmsClient(static::getConfigurationFromEnvironment()))
            ->withConfiguration(static::getTestConfiguration($httpCallback));
    }

    public static function getTestConfiguration(HttpCallBackCatcher $httpCallback): array
    {
        return ['httpCallback' => $httpCallback];
    }

    public static function getConfigurationFromEnvironment(): array
    {
        $config = [];
        $timeout = getenv('EXCITESMS_LIB_TIMEOUT');
        $environment = getenv('EXCITESMS_LIB_ENVIRONMENT');
        $accessToken = getenv('EXCITESMS_LIB_ACCESS_TOKEN');

        if ($timeout !== false && \is_numeric($timeout)) {
            $config['timeout'] = intval($timeout);
        }

        if ($environment !== false) {
            $config['environment'] = $environment;
        }

        if ($accessToken !== false) {
            $config['accessToken'] = $accessToken;
        }

        return $config;
    }
}
