<?php

declare(strict_types=1);

/*
 * ExcitesmsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ExcitesmsLib\Models;

class Data implements \JsonSerializable
{
    /**
     * @var string
     */
    private $uid;

    /**
     * @var string
     */
    private $to;

    /**
     * @var string
     */
    private $from;

    /**
     * @var string
     */
    private $message;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string
     */
    private $cost;

    /**
     * @param string $uid
     * @param string $to
     * @param string $from
     * @param string $message
     * @param string $status
     * @param string $cost
     */
    public function __construct(string $uid, string $to, string $from, string $message, string $status, string $cost)
    {
        $this->uid = $uid;
        $this->to = $to;
        $this->from = $from;
        $this->message = $message;
        $this->status = $status;
        $this->cost = $cost;
    }

    /**
     * Returns Uid.
     */
    public function getUid(): string
    {
        return $this->uid;
    }

    /**
     * Sets Uid.
     *
     * @required
     * @maps uid
     */
    public function setUid(string $uid): void
    {
        $this->uid = $uid;
    }

    /**
     * Returns To.
     */
    public function getTo(): string
    {
        return $this->to;
    }

    /**
     * Sets To.
     *
     * @required
     * @maps to
     */
    public function setTo(string $to): void
    {
        $this->to = $to;
    }

    /**
     * Returns From.
     */
    public function getFrom(): string
    {
        return $this->from;
    }

    /**
     * Sets From.
     *
     * @required
     * @maps from
     */
    public function setFrom(string $from): void
    {
        $this->from = $from;
    }

    /**
     * Returns Message.
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     *
     * @required
     * @maps message
     */
    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Cost.
     */
    public function getCost(): string
    {
        return $this->cost;
    }

    /**
     * Sets Cost.
     *
     * @required
     * @maps cost
     */
    public function setCost(string $cost): void
    {
        $this->cost = $cost;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['uid']     = $this->uid;
        $json['to']      = $this->to;
        $json['from']    = $this->from;
        $json['message'] = $this->message;
        $json['status']  = $this->status;
        $json['cost']    = $this->cost;

        return $json;
    }
}
