<?php

declare(strict_types=1);

/*
 * ExcitesmsLib
 *
 * This file was automatically generated by palnet v3.0 ( https://www.palnet.io ).
 */

namespace ExcitesmsLib\Models;

class Link implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $url;

    /**
     * @var string
     */
    private $label;

    /**
     * @var bool
     */
    private $active;

    /**
     * @param string $label
     * @param bool $active
     */
    public function __construct(string $label, bool $active)
    {
        $this->label = $label;
        $this->active = $active;
    }

    /**
     * Returns Url.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Label.
     */
    public function getLabel(): string
    {
        return $this->label;
    }

    /**
     * Sets Label.
     *
     * @required
     * @maps label
     */
    public function setLabel(string $label): void
    {
        $this->label = $label;
    }

    /**
     * Returns Active.
     */
    public function getActive(): bool
    {
        return $this->active;
    }

    /**
     * Sets Active.
     *
     * @required
     * @maps active
     */
    public function setActive(bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Encode this object to JSON
     *
     * @return mixed
     */
    public function jsonSerialize()
    {
        $json = [];
        $json['url']    = $this->url;
        $json['label']  = $this->label;
        $json['active'] = $this->active;

        return $json;
    }
}
