<?php

declare(strict_types=1);

/*
 * ExcitesmsLib
 *
 * This file was automatically generated by palnet v3.0 ( https://www.palnet.io ).
 */

namespace ExcitesmsLib;

/**
 * Environments available for API
 */
class Environment
{
    public const PRODUCTION = 'production';
}
