<?php

declare(strict_types=1);

/*
 * ExcitesmsLib
 *
 * This file was automatically generated by palnet v3.0 ( https://www.palnet.io ).
 */

namespace ExcitesmsLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const SERVER_1 = 'Server 1';
}
